In [45]:
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier

In [2]:
train = pd.read_csv("Santander_customer_classification/train_small.csv")

In [3]:
test = pd.read_csv("Santander_customer_classification/test_small.csv")

In [4]:
test.head()

ID_code    var_0   var_1    var_2   var_3    var_4   var_5   var_6  \
0   train_0   8.9255 -6.7863  11.9081  5.0930  11.4607 -9.2834  5.1187   
1   train_3  11.0604 -2.1518   8.9522  7.1957  12.5846 -1.8361  5.8428   
2   train_7  13.5580 -7.9881  13.8776  7.5985   8.6543  0.8310  5.6890   
3  train_12   8.7671 -4.6154   9.7242  7.4242   9.0254  1.4247  6.2815   
4  train_14  13.8080  5.0514  17.2611  8.5120  12.8517 -9.1622  5.7327   

     var_7   var_8  ...  var_190  var_191  var_192  var_193  var_194  var_195  \
0  18.6266 -4.9200  ...   4.4354   3.9642   3.1364   1.6910  18.5227  -2.3978   
1  14.9250 -5.8609  ...   4.4666   4.7433   0.7178   1.4214  23.0347  -1.2706   
2  22.3262  5.0647  ...  13.1700   6.5491   3.9906   5.8061  23.1407  -0.3776   
3  12.3143  5.6964  ...   0.3782   7.4382   0.0854   1.3444  17.2439  -0.0798   
4  21.0517 -4.5117  ...   1.0740   8.3220   3.2619   1.6738  17.4797  -0.0257   

   var_196  var_197  var_198  var_199  
0   7.8784   8.5635  12.7803  -1.0914  
1  -2.9275  10.2922  17.9697  -8.9996  
2   4.2178   9.4237   8.6624   3.4806  
3   5.7389   8.4897  17.0938   4.6106  
4  -3.5323   9.3439  24.4479  -5.1110  

[5 rows x 201 columns]

In [5]:
train.head()

ID_code  c    var_0   var_1    var_2   var_3    var_4   var_5   var_6  \
0  train_1  0  11.5006 -4.1473  13.8588  5.3890  12.3622  7.0433  5.6208   
1  train_2  0   8.6093 -2.7457  12.0805  7.8928  10.5825 -9.0837  6.9427   
2  train_4  0   9.8369 -1.4834  12.8746  6.6375  12.2772  2.4486  5.9405   
3  train_5  0  11.4763 -2.3182  12.6080  8.6264  10.9621  3.5609  4.5322   
4  train_6  0  11.8091 -0.0832   9.3494  4.2916  11.1355 -8.0198  6.1961   

     var_7  ...  var_190  var_191  var_192  var_193  var_194  var_195  \
0  16.5338  ...   7.6421   7.7214   2.5837  10.9516  15.4305   2.0339   
1  14.6155  ...   2.9057   9.7905   1.6704   1.6858  21.6042   3.1417   
2  19.2514  ...  -1.4905   9.5214  -0.1508   9.1942  13.2876  -1.5121   
3  15.2255  ...  -6.3068   6.6025   5.2912   0.4403  14.9452   1.0314   
4  12.0771  ...   8.7830   6.4521   3.5325   0.1777  18.3314   0.5845   

   var_196  var_197  var_198  var_199  
0   8.1267   8.7889  18.3560   1.9518  
1  -6.5213   8.2675  14.7222   0.3965  
2   3.9267   9.5031  17.9974  -8.8104  
3  -3.6241   9.7670  12.5809  -4.7602  
4   9.1104   9.1143  10.8869  -3.2097  

[5 rows x 202 columns]

In [7]:
train.describe()

c         var_0         var_1         var_2         var_3  \
count  70057.000000  70057.000000  70057.000000  70057.000000  70057.000000   
mean       0.099733     10.678757     -1.625370     10.718501      6.801363   
std        0.299646      3.037911      4.060012      2.629766      2.043351   
min        0.000000      0.597900    -15.043400      2.615000     -0.040200   
25%        0.000000      8.461000     -4.751700      8.742600      5.252000   
50%        0.000000     10.526500     -1.614100     10.589100      6.837700   
75%        0.000000     12.749600      1.371600     12.505900      8.333400   
max        1.000000     20.315000     10.376800     19.353000     13.188300   

              var_4         var_5         var_6         var_7         var_8  \
count  70057.000000  70057.000000  70057.000000  70057.000000  70057.000000   
mean      11.080280     -5.099666      5.412131     16.557562      0.284365   
std        1.627265      7.887190      0.867160      3.422813      3.335973   
min        5.490200    -29.777300      2.347300      5.349700     -9.905100   
25%        9.877400    -11.271800      4.768100     13.951300     -2.335100   
50%       11.113000     -4.844100      5.387400     16.464600      0.409100   
75%       12.268000      0.907600      6.005500     19.119800      2.946300   
max       16.671400     16.806500      8.447700     27.638900      9.482200   

       ...       var_190       var_191       var_192       var_193  \
count  ...  70057.000000  70057.000000  70057.000000  70057.000000   
mean   ...      3.257023      7.444208      1.927193      3.328773   
std    ...      4.540336      3.018182      1.481911      3.988392   
min    ...    -13.999500     -2.009400     -3.566800    -11.783400   
25%    ...     -0.022800      5.161900      0.886300      0.587800   
50%    ...      3.231400      7.341700      1.899100      3.387100   
75%    ...      6.410200      9.529300      2.952300      6.206400   
max    ...     18.342300     16.684600      7.611600     17.908600   

            var_194       var_195       var_196       var_197       var_198  \
count  70057.000000  70057.000000  70057.000000  70057.000000  70057.000000   
mean      18.008622     -0.140578      2.298631      8.906114     15.869843   
std        3.138089      1.427751      5.460012      0.920043      3.014017   
min        9.594900     -4.644200    -14.020400      5.960600      6.299300   
25%       15.640500     -1.164000     -1.956100      8.253600     13.819700   
50%       17.975900     -0.169000      2.390700      8.886000     15.931700   
75%       20.421000      0.828300      6.573400      9.589400     18.071500   
max       27.928800      4.075600     16.226600     11.843900     26.079100   

            var_199  
count  70057.000000  
mean      -3.323176  
std       10.438217  
min      -38.852800  
25%      -11.236200  
50%       -2.800100  
75%        4.855300  
max       27.531900  

[8 rows x 201 columns]

MEAN c (class) is 0.099, which means only 9% of classes is classified as 1

In [46]:
train_values = train.values
X = train_values[:,2:]
Y = train_values[:,1]
Y = Y.astype('int')

In [47]:
X


array([[11.5006, -4.1473, 13.8588, ..., 8.7889, 18.355999999999998,
        1.9518],
       [8.6093, -2.7457, 12.0805, ..., 8.2675, 14.7222, 0.3965],
       [9.8369, -1.4834, 12.8746, ..., 9.5031, 17.9974, -8.8104],
       ...,
       [13.2152, -5.8006, 9.726, ..., 8.9709, 14.5405, 6.1149],
       [4.9149, -2.4484, 16.7052, ..., 6.7419, 15.9054, 0.3388],
       [9.7148, -8.6098, 13.6104, ..., 10.0342, 15.5289, -13.9001]],
      dtype=object)

In [48]:
Y

array([0, 0, 0, ..., 0, 0, 0])

In [50]:
x_train, x_val, y_train, y_val = train_test_split(X, Y, test_size=0.10, random_state=42)
clf = RandomForestClassifier(n_jobs=4, random_state=0)
clf.fit(x_train, y_train)
clf.predict(x_val)

array([0, 0, 0, ..., 0, 0, 0])

In [52]:
clf.feature_importances_

array([0.00591507, 0.00674944, 0.00779951, 0.00399611, 0.00469508,
       0.00540667, 0.00613961, 0.00437568, 0.00386782, 0.00551298,
       0.004459  , 0.00378167, 0.00918902, 0.00654212, 0.00439599,
       0.00387518, 0.00407375, 0.00383966, 0.0054761 , 0.0041712 ,
       0.00448454, 0.00576276, 0.00742842, 0.00497609, 0.00502985,
       0.00463509, 0.00857509, 0.00383872, 0.00362469, 0.00387808,
       0.00413676, 0.00391173, 0.00461808, 0.0068245 , 0.00670411,
       0.00532163, 0.00418718, 0.00435623, 0.00371209, 0.00405963,
       0.00692697, 0.00367899, 0.00344595, 0.00531142, 0.00629673,
       0.00422109, 0.0044396 , 0.00419606, 0.00442556, 0.00503507,
       0.00398433, 0.00505668, 0.00401964, 0.00911083, 0.00385292,
       0.00456446, 0.00510053, 0.00322768, 0.00428062, 0.00419633,
       0.00439878, 0.00353476, 0.00384003, 0.0041542 , 0.00427789,
       0.00435814, 0.00400983, 0.00472979, 0.00438431, 0.00404873,
       0.00474207, 0.0036276 , 0.0038796 , 0.00409194, 0.00377

In [29]:
kfold = model_selection.KFold(n_splits=4, random_state=0)
model = AdaBoostClassifier(n_estimators=1, random_state=0)
results = model_selection.cross_val_score(model, train_x, train_y, cv=kfold)
print(results.mean())

0.9006664767611243
